#!/bin/bash
#
# Compile everything (requires gcc and g+ compiles and the netcdf libraries)
curr=`pwd`

# make C library (you can make other language libraries if desired)
cd src/sirlib/c
make -f Makefile
cd $curr

# compile production code
cd src/prod/
make_meas_meta_make
make_meas_meta_setup
make_meas_meta_sir
make_meas_meta_bgi
# note: sir2netcdf requires prior installation of the netcdf libraries
# and modification of the make script to point to them
#make_sir2netcdf
cd $curr

# testing code
cd testing/cproj
make_test_ease2
cd $curr

# compile utilities
cd src/sir2gifs
make_sir2gifs6b
cd $curr

# note: sirtool requires prior installation of the fltk library
# and is an optional inclusion
cd src/sirtool
make -f Makefile
make -f Makefile clean
cd $curr

