#!/bin/sh
#set -x
#
# fortran 77 compile script for BYU sir library
#
# uncomment appropriate compile line.
#
#fort='fort77 -static'  # SGI fort77
#fort='f77 -32'         # SGI fort77 -o32
#fort='f90 -static '    # SGI fort90 (w/o 90 code)
#fort='f77 -K'          # IBM SP
#fort='f77 -ext_names=plain -cg92 -w -e -Nl99 -libmil -native -O5' # Sun-OS
#fort='fort77 +es +E4 -K'                 # hp-ux fort77
#fort='f90 -K +gformat77 +es +DAportable '   # hp-ux f90 (w/o 90 code)
fort='g77 -fugly-assumed -fugly-logint -fno-automatic -m64 -O3 -fomit-frame-pointer  -fpeel-loops -ftracer -funswitch-loops -ffixed-line-length-none'
#
echo 'fortran compile command ' $fort
#
rm *.o
rm libfsirf.a
#
$fort -c lib/arctand.f  -Ilib/
$fort -c lib/easegrid.f -Ilib/
$fort -c lib/f2ipix.f   -Ilib/
$fort -c lib/ieasegrid.f -Ilib/
$fort -c lib/ilambert1.f -Ilib/
$fort -c lib/ipolster.f -Ilib/
$fort -c lib/lambert1.f -Ilib/
$fort -c lib/latlon2pix.f -Ilib/
$fort -c lib/pix2latlon.f -Ilib/
$fort -c lib/polster.f -Ilib/
$fort -c lib/length.f -Ilib/
$fort -c lib/printhead.f -Ilib/
$fort -c lib/printhead3.f -Ilib/
$fort -c lib/readsirf.f -Ilib/
$fort -c lib/readsirf_block.f -Ilib/
$fort -c lib/readsirhead.f -Ilib/
$fort -c lib/readsirhead3.f -Ilib/
$fort -c lib/swapbuf.f -Ilib/
$fort -c lib/writesir.f -Ilib/
$fort -c lib/writesir3.f -Ilib/
$fort -c lib/sirupdate.f -Ilib/
#
# note: the SIREZ.f routines are based on extensions to fortran
# and do not work on many compilers.  Comment out if compiler doesn't like.
#
## $fort -c lib/SIREZ.f    
#
ar cr libfsirf.a *.o
rm *.o
