	SUBROUTINE SIRUPDATE(STVAL,NHTYPE,NSX,NSY,ANODATA,VMIN,VMAX)
C
C     UPDATE SIR HEADER INFO FOR OLD STYLE HEADERS
C
	IF (NHTYPE.EQ.1) THEN   ! OLD STYLE HEADER
C
C	DETERMINE MAX/MIN OF DATA ARRAY
C
           SMIN=1.E25
           SMAX=-1.E25
           DO NN1=0,NSY-1
              DO NN2=1,NSX
                 INDEX = NN1*NSX + NN2
                 IF (STVAL(INDEX).LT.SMIN) SMIN=STVAL(INDEX)
                 IF (STVAL(INDEX).GT.SMAX) SMAX=STVAL(INDEX)
              END DO
           END DO
	   ANODATA=SMIN
	   VMIN=SMIN
	   VMAX=SMAX
	   IF (ABS(SMIN+32.0).LT.2) THEN
	      ANODATA=-32.0
	      VMIN=-32.0
	   ELSE IF (ABS(SMIN+3.2).LT.2) THEN
	      ANODATA=-3.2
	      VMIN=-3.0
	   ENDIF
	   IF (ABS(SMAX).LT.2) THEN
	      VMAX=0.0
	   ENDIF
	ENDIF
        RETURN
        END
