name: do-bumpversion
run-name: ${{ github.actor }} is running do-bumpversion
on: [push]
jobs:
  do-bumpversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "This does nothing"
